import type { Metadata } from "next";
import { UrqlProvider } from "@/components/UrqlProvider";
import "./globals.css";
import { Toaster } from "@/components/ui/toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-background">
      <UrqlProvider>
        <body>{children}</body>
        <Toaster />
      </UrqlProvider>
    </html>
  );
}
